services:

  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/log/nginx:/var/log/nginx
      - .:/var/www/html
    depends_on:
      - php-fpm
      - database
    networks:
      - app-network

  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    ports:
      - 9000:9000
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./.docker/php-fpm/conf.d/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - app-network

  database:
    container_name: ${APP_NAME}_database
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/data/db/mysql:/var/lib/mysql
      - ./.docker/mysql/conf.d/my.conf:/etc/mysql/conf.d/my.cnf
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
